for j3 = 1 : 251,
  
  for j4 = 1 : 821, 
    
    Raw.G_S0_Lin(j3,j4) = Raw.P_P1_Lin(j3,j4)./Exc.Pwr(j3,1);    % Rt ,
    Raw.G_I0_Lin(j3,j4) = Raw.P_P2_Lin(j3,j4)./Exc.Pwr(j3,2);    % Rt ,
  
    Raw.G_S0_Log(j3,j4) = 10*log10( Raw.G_S0_Lin(j3,j4) );       % dB ,
    Raw.G_I0_Log(j3,j4) = 10*log10( Raw.G_I0_Lin(j3,j4) );       % dB ,
    
  end;
  
 [Max.G_S0_max(j3, 1),Max.G_S0_max(j3, 2)] = max(Raw.G_S0_Log(j3,:));
  Max.G_S0_max(j3, 3) = Exc.Phi(Max.G_S0_max(j3, 2),3);
 [Max.G_I0_max(j3, 1),Max.G_I0_max(j3, 2)] = max(Raw.G_I0_Log(j3,:));
  Max.G_I0_max(j3, 3) = Exc.Phi(Max.G_I0_max(j3, 2),3);
 
%   Max.P_P1_max(j3, 1) = Raw.P_P1_Log(j3,Max.G_SI_max(j3, 2));
%   Max.P_P2_max(j3, 1) = Raw.P_P2_Log(j3,Max.G_SI_max(j3, 2));
%   Max.P_SI_max(j3, 1) = Raw.P_SI_Log(j3,Max.G_SI_max(j3, 2));
%   Max.P_P3_max(j3, 1) = Raw.P_P3_Log(j3,Max.G_SI_max(j3, 2));
%   Max.P_P4_max(j3, 1) = Raw.P_P4_Log(j3,Max.G_SI_max(j3, 2));
%   Max.P_S1_max(j3, 1) = Raw.P_S1_Log(j3,Max.G_SI_max(j3, 2));
%   Max.P_S2_max(j3, 1) = Raw.P_S2_Log(j3,Max.G_SI_max(j3, 2));

 [Max.G_S0_min(j3, 1),Max.G_S0_min(j3, 2)] = min(Raw.G_S0_Log(j3,:));
  Max.G_S0_min(j3, 3) = Exc.Phi(Max.G_S0_min(j3, 2),3);
 [Max.G_I0_min(j3, 1),Max.G_I0_min(j3, 2)] = min(Raw.G_I0_Log(j3,:));
  Max.G_I0_min(j3, 3) = Exc.Phi(Max.G_I0_min(j3, 2),3);

  Max.G_S0_zro_m(j3,j1) = Raw.G_S0_Log(j3,1);
  Max.G_S0_max_m(j3,j1) = Max.G_S0_max(j3,1);
  Max.G_S0_min_m(j3,j1) = Max.G_S0_min(j3,1);
  Max.G_S0_PSER_m(j3,j1) = Max.G_S0_max(j3,1)-Max.G_S0_min(j3,1);
  Max.G_S0_PSGA_m(j3,j1) = Max.G_S0_max(j3,1)+Max.G_S0_min(j3,1);
  Max.G_S0_max_Ph_m(j3,j1) = Max.G_S0_max(j3,3);
  Max.G_S0_min_Ph_m(j3,j1) = Max.G_S0_min(j3,3);

end;

%%
figure(01);
set(gcf,'Position',[100 100 600 450]);
hold on;

f01     = zeros(10, 1);

f01(01) = plot(10*log10((Exc.Pwr(:,1)+Exc.Pwr(:,2))./Exc.Pwr(:,3)), Max.G_S0_max_m(:,1),...
  'Color',    [0.9 0.0 0.0],...
  'LineStyle',' -',...
  'LineWidth',1.25);
f01(02) = plot(10*log10((Exc.Pwr(:,1)+Exc.Pwr(:,2))./Exc.Pwr(:,3)), Max.G_S0_min_m(:,1),...
  'Color',    [0.0 0.0 0.9],...
  'LineStyle',' -',...
  'LineWidth',1.25);
f01(03) = plot(10*log10((Exc.Pwr(:,1)+Exc.Pwr(:,2))./Exc.Pwr(:,3)), Max.G_S0_PSER_m(:,1),...
  'Color',    [0.9 0.5 0.0],...
  'LineStyle',' -',...
  'LineWidth',1.25);
f01(04) = plot(10*log10((Exc.Pwr(:,1)+Exc.Pwr(:,2))./Exc.Pwr(:,3)), Max.G_S0_PSGA_m(:,1),...
  'Color',    [0.0 0.5 0.0],...
  'LineStyle',' -',...
  'LineWidth',1.25);

% set(gca,'xLim', [  0.0, 1.0],...
%         'xTick',(- 1.0: 0.1 :+1.5),...
%         'yLim', [floor(min(Max.G_SI_max_m(:,1)))-1, ceil(max(Max.G_SI_max_m(:,1)))+1],...
%         'yTick',[floor(min(Max.G_SI_max_m(:,1)))-1:...
%                  5.0:...
%                   ceil(max(Max.G_SI_max_m(:,1)))+1],...
set(gca,'xLim', [- 30.0,       + 20.0],...
        'xTick',(- 50.0:  5.0 :+ 40.0),...
        'yLim', [- 60.0,       + 60.0],...
        'yTick',(-100.0: 10.0 :+100.0),...
  'FontName','Arial',...
  'FontSize',12,...
  'FontWeight','Normal');
grid on;
%
xlabel('P_{Signal}/P_{Pump}', ...
  'FontName','Arial',...
  'FontSize',12,...
  'FontWeight','Normal');
ylabel('Signal gain (dB)', ...
  'FontName','Arial',...
  'FontSize',12,...
  'FontWeight','Normal');
%
if SimMod.FLD_nPWR, % simulation with field
  title({'Signal gain vs. Signal power pump power ratio'; ...
   ['7-wave CWODE, \delta\lambda_{OFS}=',num2str(SimMod.Wvlen_ofs*1e9,'%3.1f'),'nm',...
                ', \Delta\lambda_{PP}=', num2str(ExcSet.PP_Sp_Wvl,    '%3.1f'),'nm']},...
    'FontName','Arial',...
    'FontSize',10,...
    'FontWeight','Normal');
else % SimMod.FLD_nPWR == 0, simulation with power and phase
  if SimMod.PSA_nPIA, % simulation in PSA

  else % SimMod.PSA_nPIA == 0, simulation in PIA

  end; % SimMod.PSA_nPIA
end; % if-else SimMod.FLD_nPWR
%
legend([f01(01),f01(02),f01(03),f01(04)], ...
  {'\theta_{rel,Max}',...
   '\theta_{rel,Min}',...
   'PSER',...
   'PSGA'}, ...
  'FontName','Arial',...
  'FontSize',10,...
  'FontWeight','Normal',...
  'Location','Northeast');  